site_name: Flameblock Documentation
theme: 
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'orange'
  logo:
    icon: 'assessment'

nav:
  - Introduction: index.md
  - Solution Considerations: considerations.md
  - Architecture: arch.md
  - Source Code and Deployment: examples.md

markdown_extensions:
  - markdown_include.include
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.3.1/dist/mermaid.min.js
