apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nsolid-license
  namespace: flameblock
spec:
  encryptedData:
    license: AgCznfrsZQzczs/83OwPW5PSu2GHo0TWi44BWRsNEJMyOXkBrs1GGsVDnZMc3/1TCv5NCuxrIlBiISWEQrJ3pYVgjj9FLMUxSebRfpdAJctNY8axVy0dP4OMiGhDb12/p07+2ywqztkn57spjya9WGbbj9fpYH0y9zIVLjVHbnmNh/3ZTUB6IxfISFRHkpqKvcXgto4X65avknavCtb4XYOYzaaO6Nrw/oQh539fj4Me1h7etoQLFm3JEY6n804A8YJztWhaSLYYzPy0OdliQJM0oZJ8YnBqETAzKZg/CXHzEbGHMM/zEQNvVl37RwWgY97sfxJdZ9IyeDTEOPBKYbx6OwoKvnzjrety5tpCXsFI9riqDzMSI7HVwrz8N6s5eRe0ax9fNzVS6dLgYwHYlG7JRA3eLQDMT6cF3DZsdTvHyBC6veaeticykF+jc0dgUB1qicXS/4UJ94OGnnon/Lrnzu6dmr6uqzLKH39UKofswsxLpW4qIZNXjbQ4H5SKYJkmfYiLdqKo97V3dEwfEyDjAq8b6z7X7SDsCFn6SxZK2uyoq2oGhOqHMvj4fCYllAxZEpoG4bJ6G/qFnq919Aat2LgFWw8OnyVswspBg8mGExEfVLWCM8Tm8WZerJjXjzW+7BGMELOG1X5YpCRYsO32tjY308xxCCGDPnILbyhCZhwYrRSYB1i//4U8YToliPu/6IB/A2c/y1cIyKGcFlnIWzHTAq6nnzU/9pseblkJ4OBcBwo=
  template:
    metadata:
      name: nsolid-license
      namespace: flameblock
    type: Opaque
